carousel_software:
  type: enum
  default: "Swiper"
  choices:
    - "Splide"

image_carousel_placeholder:
  type: upload
  default: "placeholder_image"

# image_carousel_placeholder_height:
#   type: integer
#   default: 200
#   min: 1

# image_carousel_placeholder_width:
#   type: integer
#   default: 300
#   min: 1

show_pagination_buttons:
  type: bool
  default: true

# autoplay:
#   type: bool
#   default: true

# autoplay_interval:
#   type: integer
#   default: 5000

# loop:
#   type: bool
#   default: true

# enable_thumbs:
#   type: bool
#   default: false

# thumbs_direction:
#  type: enum
#  default: "horizontal"
#  choices:
#    - "vertical"

image_transition_animation:
  type: enum
  default: "slide"
  choices:
    - "cube"
    - "fade"
    - "cards"

pagination_button_color:
  type: string
  default: ""

active_pagination_button_color:
  type: string
  default: ""
